cluster.name: "docker-cluster"


discovery.type: single-node
network.host: 0.0.0.0

xpack.license.self_generated.type: basic
xpack.security.enabled: false
xpack.security.transport.ssl.enabled: false
xpack.monitoring.collection.enabled: true