# Generated by Django 4.1.1 on 2022-09-21 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebookk', '0003_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user_to',
        ),
        migrations.AddField(
            model_name='subscription',
            name='user_from',
            field=models.ManyToManyField(related_name='users_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user_to',
            field=models.ManyToManyField(related_name='users_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
