# Generated by Django 4.1.1 on 2022-09-21 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebookk', '0004_remove_subscription_user_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user_to',
        ),
        migrations.AddField(
            model_name='subscription',
            name='page_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pages_to', to='facebookk.page'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user_from',
        ),
        migrations.AddField(
            model_name='subscription',
            name='user_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
