# Generated by Django 4.1.1 on 2022-09-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebookk', '0007_unlike_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lposts_to', related_query_name='like_fil', to='facebookk.post'),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', to='facebookk.tag'),
        ),
        migrations.AlterField(
            model_name='unlike',
            name='post_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uposts_to', related_query_name='unlike_fil', to='facebookk.post'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
