# Generated by Django 4.1.1 on 2022-10-02 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebookk', '0009_alter_page_follow_requests_alter_page_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follows', related_query_name='allfol', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
